### ISSUE TITLE
div III feedback

### ISSUE THREAD

**Issue by mariumtapal** [katelyndiaz/ggRtsy#2]
1. Passes `install_github`: ✅ 
2. Documentation builds: ✅
3. Passes R CMD check: ✅
`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`
4. Results of `devtools::test()`: 
[ FAIL 0 | WARN 1 | SKIP 0 | PASS 4 ]

@beanumber

**Comment by beanumber** [comment]
Really nice job!

- A couple of your examples were not working. See #3 for suggested fixes.
